/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ROOT;

import AUTH.Authenticate;
import Libraries.Auth;
import Libraries.Database;
import Libraries.Session;
import Libraries.Variabel.Position;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author surya
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        navItems1 = new javax.swing.JButton();
        navItems2 = new javax.swing.JButton();
        navItems3 = new javax.swing.JButton();
        navSettings = new javax.swing.JButton();
        navExit = new javax.swing.JButton();
        navItems4 = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");
        setLocation(Position.Center("screenX"),Position.Center("screenY"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidebar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navItems1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_alt_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems1.setText("Pesanan");
        navItems1.setAlignmentY(0.0F);
        navItems1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems1ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 184, -1));

        navItems2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/receipt_long_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems2.setText("Laporan");
        navItems2.setAlignmentY(0.0F);
        navItems2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems2ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 42, 184, -1));

        navItems3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manage_accounts_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems3.setText("Karyawan");
        navItems3.setAlignmentY(0.0F);
        navItems3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems3ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems3, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 76, 184, -1));

        navSettings.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navSettings.setText("Pengaturan");
        navSettings.setAlignmentY(0.0F);
        navSettings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navSettingsActionPerformed(evt);
            }
        });
        Sidebar.add(navSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 330, 184, -1));

        navExit.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navExit.setText("Keluar");
        navExit.setAlignmentY(0.0F);
        navExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navExitActionPerformed(evt);
            }
        });
        Sidebar.add(navExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 364, 184, -1));

        navItems4.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/format_list_bulleted_add_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems4.setText("Kendaraan");
        navItems4.setAlignmentY(0.0F);
        navItems4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems4ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 110, 184, -1));

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nama Pengguna");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 40));

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selamat Datang");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 44, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(Auth.isLoggedIn() == false){
            dispose();
            
            SwingUtilities.invokeLater(() -> new Authenticate().setVisible(true));
        }
        try {
            jLabel4.setText(Database.SELECT("SELECT Nama FROM karyawan WHERE Username = ?"));
        } catch (Exception ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void navExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navExitActionPerformed
        Session.Destroy();
        dispose();
        SwingUtilities.invokeLater(() -> new Authenticate().setVisible(true));
    }//GEN-LAST:event_navExitActionPerformed

    private void navItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems1ActionPerformed
        dispose();
        SwingUtilities.invokeLater(() -> new ROOT.Pesanan.Main().setVisible(true));
    }//GEN-LAST:event_navItems1ActionPerformed

    private void navItems4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems4ActionPerformed
        dispose();
        SwingUtilities.invokeLater(() -> new ROOT.Kendaraan.Main().setVisible(true));
    }//GEN-LAST:event_navItems4ActionPerformed

    private void navItems2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems2ActionPerformed
        
    }//GEN-LAST:event_navItems2ActionPerformed

    private void navItems3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems3ActionPerformed
        dispose();
        SwingUtilities.invokeLater(() -> new ROOT.Karyawan.Main().setVisible(true));
    }//GEN-LAST:event_navItems3ActionPerformed

    private void navSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navSettingsActionPerformed
        
    }//GEN-LAST:event_navSettingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton navExit;
    private javax.swing.JButton navItems1;
    private javax.swing.JButton navItems2;
    private javax.swing.JButton navItems3;
    private javax.swing.JButton navItems4;
    private javax.swing.JButton navSettings;
    // End of variables declaration//GEN-END:variables
}
