/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package USER;

import AUTH.Authenticate;
import Libraries.Auth;
import Libraries.Database;
import static Libraries.Images.ResizeImages;
import Libraries.Session;
import Libraries.Variabel.Position;
import ROOT.Kendaraan.Main;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import static Libraries.Database.DBNAME;
import static Libraries.Database.DBPASS;
import static Libraries.Database.DBUSER;
import static Libraries.Variabel.selectedDetails;

/**
 *
 * @author surya
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }
    
    private int intDetail0,intDetail1,intDetail2,intDetail3,intDetail4,intDetail5;
    private int selectorOffset = 0;
    private ImageIcon objG0L3,objG1L3,objG2L3,objG3L3,objG4L3,objG5L3;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        navItems1 = new javax.swing.JButton();
        navItems2 = new javax.swing.JButton();
        navSettings = new javax.swing.JButton();
        navCS = new javax.swing.JButton();
        navExit = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jG0 = new javax.swing.JPanel();
        cG0L3 = new javax.swing.JLabel(objG0L3);
        cG0L0 = new javax.swing.JLabel();
        cG0L1 = new javax.swing.JLabel();
        cG0L2 = new javax.swing.JLabel();
        jDetail0 = new javax.swing.JLabel();
        jG2 = new javax.swing.JPanel();
        cG2L3 = new javax.swing.JLabel(objG2L3);
        cG2L0 = new javax.swing.JLabel();
        cG2L1 = new javax.swing.JLabel();
        cG2L2 = new javax.swing.JLabel();
        jDetail1 = new javax.swing.JLabel();
        jG4 = new javax.swing.JPanel();
        cG4L3 = new javax.swing.JLabel(objG4L3);
        cG4L0 = new javax.swing.JLabel();
        cG4L1 = new javax.swing.JLabel();
        cG4L2 = new javax.swing.JLabel();
        jDetail2 = new javax.swing.JLabel();
        jG1 = new javax.swing.JPanel();
        cG1L3 = new javax.swing.JLabel(objG1L3);
        cG1L0 = new javax.swing.JLabel();
        cG1L1 = new javax.swing.JLabel();
        cG1L2 = new javax.swing.JLabel();
        jDetail3 = new javax.swing.JLabel();
        jG3 = new javax.swing.JPanel();
        cG3L3 = new javax.swing.JLabel(objG3L3);
        cG3L0 = new javax.swing.JLabel();
        cG3L1 = new javax.swing.JLabel();
        cG3L2 = new javax.swing.JLabel();
        jDetail4 = new javax.swing.JLabel();
        jG5 = new javax.swing.JPanel();
        cG5L3 = new javax.swing.JLabel(objG5L3);
        cG5L0 = new javax.swing.JLabel();
        cG5L1 = new javax.swing.JLabel();
        cG5L2 = new javax.swing.JLabel();
        jDetail5 = new javax.swing.JLabel();
        jBack = new javax.swing.JLabel();
        jNext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Beranda");
        setLocation(Position.Center("screenX",1020),Position.Center("screenY",545));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidebar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navItems1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list_alt_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems1.setText("Pesanan Saya");
        navItems1.setAlignmentY(0.0F);
        navItems1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems1ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 184, -1));

        navItems2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/order_approve_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems2.setText("Riwayat Pemesanan");
        navItems2.setAlignmentY(0.0F);
        navItems2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sidebar.add(navItems2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 42, 184, 28));

        navSettings.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navSettings.setText("Pengaturan");
        navSettings.setAlignmentY(0.0F);
        navSettings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navSettings.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sidebar.add(navSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 437, 184, 28));

        navCS.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/support_agent_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navCS.setText("Layanan Pengguna");
        navCS.setAlignmentY(0.0F);
        navCS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navCS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navCS.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Sidebar.add(navCS, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 473, 184, 28));

        navExit.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navExit.setText("Keluar");
        navExit.setAlignmentY(0.0F);
        navExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navExit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navExitActionPerformed(evt);
            }
        });
        Sidebar.add(navExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 509, 184, 28));

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 545));

        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nama Pengguna");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 820, 40));

        jG0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG0.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cG0L3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cG0L3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG0.add(cG0L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 135));

        cG0L0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG0L0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG0L0.setText("Merek");
        cG0L0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG0.add(cG0L0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, 30));

        cG0L1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG0L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG0L1.setText("Model");
        cG0L1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG0.add(cG0L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, 140, 30));

        cG0L2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG0L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG0L2.setText("Seater");
        cG0L2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG0.add(cG0L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));

        jDetail0.setBackground(new java.awt.Color(102, 102, 102));
        jDetail0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDetail0.setForeground(new java.awt.Color(0, 51, 255));
        jDetail0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDetail0.setText("Detail Kendaraan");
        jDetail0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDetail0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDetail0MouseClicked(evt);
            }
        });
        jG0.add(jDetail0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, 140, 30));

        getContentPane().add(jG0, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 410, 155));

        jG2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cG2L3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cG2L3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG2.add(cG2L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 135));

        cG2L0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG2L0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG2L0.setText("Merek");
        cG2L0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG2.add(cG2L0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, 30));

        cG2L1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG2L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG2L1.setText("Model");
        cG2L1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG2.add(cG2L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, 140, 30));

        cG2L2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG2L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG2L2.setText("Seater");
        cG2L2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG2.add(cG2L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));

        jDetail1.setBackground(new java.awt.Color(102, 102, 102));
        jDetail1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDetail1.setForeground(new java.awt.Color(0, 51, 255));
        jDetail1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDetail1.setText("Detail Kendaraan");
        jDetail1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDetail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDetail1MouseClicked(evt);
            }
        });
        jG2.add(jDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, 140, 30));

        getContentPane().add(jG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 195, 410, 155));

        jG4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cG4L3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cG4L3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG4.add(cG4L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 135));

        cG4L0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG4L0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG4L0.setText("Merek");
        cG4L0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG4.add(cG4L0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, 30));

        cG4L1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG4L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG4L1.setText("Model");
        cG4L1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG4.add(cG4L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, 140, 30));

        cG4L2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG4L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG4L2.setText("Seater");
        cG4L2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG4.add(cG4L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));

        jDetail2.setBackground(new java.awt.Color(102, 102, 102));
        jDetail2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDetail2.setForeground(new java.awt.Color(0, 51, 255));
        jDetail2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDetail2.setText("Detail Kendaraan");
        jDetail2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDetail2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDetail2MouseClicked(evt);
            }
        });
        jG4.add(jDetail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, 140, 30));

        getContentPane().add(jG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 410, 155));

        jG1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cG1L3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cG1L3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG1.add(cG1L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 135));

        cG1L0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG1L0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG1L0.setText("Merek");
        cG1L0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG1.add(cG1L0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, 30));

        cG1L1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG1L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG1L1.setText("Model");
        cG1L1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG1.add(cG1L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, 140, 30));

        cG1L2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG1L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG1L2.setText("Seater");
        cG1L2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG1.add(cG1L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));

        jDetail3.setBackground(new java.awt.Color(102, 102, 102));
        jDetail3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDetail3.setForeground(new java.awt.Color(0, 51, 255));
        jDetail3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDetail3.setText("Detail Kendaraan");
        jDetail3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDetail3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDetail3MouseClicked(evt);
            }
        });
        jG1.add(jDetail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, 140, 30));

        getContentPane().add(jG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 410, 155));

        jG3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cG3L3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cG3L3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG3.add(cG3L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 135));

        cG3L0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG3L0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG3L0.setText("Merek");
        cG3L0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG3.add(cG3L0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, 30));

        cG3L1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG3L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG3L1.setText("Model");
        cG3L1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG3.add(cG3L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, 140, 30));

        cG3L2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG3L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG3L2.setText("Seater");
        cG3L2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG3.add(cG3L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));

        jDetail4.setBackground(new java.awt.Color(102, 102, 102));
        jDetail4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDetail4.setForeground(new java.awt.Color(0, 51, 255));
        jDetail4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDetail4.setText("Detail Kendaraan");
        jDetail4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDetail4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDetail4MouseClicked(evt);
            }
        });
        jG3.add(jDetail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, 140, 30));

        getContentPane().add(jG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 195, 410, 155));

        jG5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cG5L3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cG5L3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG5.add(cG5L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 135));

        cG5L0.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG5L0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG5L0.setText("Merek");
        cG5L0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG5.add(cG5L0, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 140, 30));

        cG5L1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG5L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG5L1.setText("Model");
        cG5L1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG5.add(cG5L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 45, 140, 30));

        cG5L2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        cG5L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cG5L2.setText("Seater");
        cG5L2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jG5.add(cG5L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 140, 30));

        jDetail5.setBackground(new java.awt.Color(102, 102, 102));
        jDetail5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jDetail5.setForeground(new java.awt.Color(0, 51, 255));
        jDetail5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDetail5.setText("Detail Kendaraan");
        jDetail5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDetail5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDetail5MouseClicked(evt);
            }
        });
        jG5.add(jDetail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 115, 140, 30));

        getContentPane().add(jG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 410, 155));

        jBack.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jBack.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_circle_left_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jBack.setText("Back");
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });
        getContentPane().add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 515, 80, 20));

        jNext.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jNext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_circle_right_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jNext.setText("Next");
        jNext.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNextMouseClicked(evt);
            }
        });
        getContentPane().add(jNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 515, 80, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(Auth.isLoggedIn() == false){
            dispose();
            
            SwingUtilities.invokeLater(() -> new Authenticate().setVisible(true));
        }
        try {
            jLabel4.setText(Database.SELECT("SELECT Nama FROM penyewa WHERE Username = ?"));
        } catch (Exception ex) {
            Logger.getLogger(Beranda.class.getName()).log(Level.SEVERE, null, ex);
        }
        try(Connection DB = DriverManager.getConnection(DBNAME, DBUSER, DBPASS)){
            String Query = "SELECT ID, Merek, Model, Kapasitas, Gambar FROM mobil WHERE NOT(Status='Dipakai' OR Status='Perbaikan' OR Status='Dipesan') LIMIT 6 OFFSET 0";
            try(PreparedStatement Statements = DB.prepareStatement(Query)){
                ResultSet Results = Statements.executeQuery();
                int index = 0;
                while(Results.next()){
                    switch (index++){
                        case 0 ->{
                            intDetail0 = Results.getInt("ID");
                            cG0L0.setText(Results.getString("Merek"));
                            cG0L1.setText(Results.getString("Model"));
                            cG0L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG0L3 = ResizeImages(objGambar,240,135);
                            cG0L3.setIcon(objG0L3);
                        }
                        case 1 ->{
                            intDetail1 = Results.getInt("ID");
                            cG1L0.setText(Results.getString("Merek"));
                            cG1L1.setText(Results.getString("Model"));
                            cG1L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG1L3 = ResizeImages(objGambar,240,135);
                            cG1L3.setIcon(objG1L3);
                        }
                        case 2 ->{
                            intDetail2 = Results.getInt("ID");
                            cG2L0.setText(Results.getString("Merek"));
                            cG2L1.setText(Results.getString("Model"));
                            cG2L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG2L3 = ResizeImages(objGambar,240,135);
                            cG2L3.setIcon(objG2L3);
                        }
                        case 3 ->{
                            intDetail3 = Results.getInt("ID");
                            cG3L0.setText(Results.getString("Merek"));
                            cG3L1.setText(Results.getString("Model"));
                            cG3L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG3L3 = ResizeImages(objGambar,240,135);
                            cG3L3.setIcon(objG3L3);
                        }
                        case 4 ->{
                            intDetail4 = Results.getInt("ID");
                            cG4L0.setText(Results.getString("Merek"));
                            cG4L1.setText(Results.getString("Model"));
                            cG4L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG4L3 = ResizeImages(objGambar,240,135);
                            cG4L3.setIcon(objG4L3);
                        }
                        case 5 ->{
                            intDetail5 = Results.getInt("ID");
                            cG5L0.setText(Results.getString("Merek"));
                            cG5L1.setText(Results.getString("Model"));
                            cG5L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG5L3 = ResizeImages(objGambar,240,135);
                            cG5L3.setIcon(objG5L3);
                        }
                        default ->{
                            // Nothing
                        }
                    }
                }
            }
        } catch (SQLException ex){
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void navExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navExitActionPerformed
        Session.Destroy();
        dispose();
        SwingUtilities.invokeLater(() -> new Authenticate().setVisible(true));
    }//GEN-LAST:event_navExitActionPerformed

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        jG0.setVisible(false);
        jG1.setVisible(false);
        jG2.setVisible(false);
        jG3.setVisible(false);
        jG4.setVisible(false);
        jG5.setVisible(false);
        
        selectorOffset = !(selectorOffset <= 6) ? selectorOffset - 6 : 0;
        try(Connection DB = DriverManager.getConnection(DBNAME, DBUSER, DBPASS)){
            String Query = "SELECT ID, Merek, Model, Kapasitas, Gambar FROM mobil WHERE NOT(Status='Dipakai' OR Status='Perbaikan' OR Status='Dipesan') LIMIT 6 OFFSET ?";
            try(PreparedStatement Statements = DB.prepareStatement(Query)){
                Statements.setInt(1, selectorOffset);
                ResultSet Results = Statements.executeQuery();
                int index = 0;
                while(Results.next()){
                    switch (index++){
                        case 0 ->{
                            jG0.setVisible(true);
                            intDetail0 = Results.getInt("ID");
                            cG0L0.setText(Results.getString("Merek"));
                            cG0L1.setText(Results.getString("Model"));
                            cG0L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG0L3 = ResizeImages(objGambar,240,135);
                            cG0L3.setIcon(objG0L3);
                        }
                        case 1 ->{
                            jG1.setVisible(true);
                            intDetail1 = Results.getInt("ID");
                            cG1L0.setText(Results.getString("Merek"));
                            cG1L1.setText(Results.getString("Model"));
                            cG1L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG1L3 = ResizeImages(objGambar,240,135);
                            cG1L3.setIcon(objG1L3);
                        }
                        case 2 ->{
                            jG2.setVisible(true);
                            intDetail2 = Results.getInt("ID");
                            cG2L0.setText(Results.getString("Merek"));
                            cG2L1.setText(Results.getString("Model"));
                            cG2L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG2L3 = ResizeImages(objGambar,240,135);
                            cG2L3.setIcon(objG2L3);
                        }
                        case 3 ->{
                            jG3.setVisible(true);
                            intDetail3 = Results.getInt("ID");
                            cG3L0.setText(Results.getString("Merek"));
                            cG3L1.setText(Results.getString("Model"));
                            cG3L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG3L3 = ResizeImages(objGambar,240,135);
                            cG3L3.setIcon(objG3L3);
                        }
                        case 4 ->{
                            jG4.setVisible(true);
                            intDetail4 = Results.getInt("ID");
                            cG4L0.setText(Results.getString("Merek"));
                            cG4L1.setText(Results.getString("Model"));
                            cG4L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG4L3 = ResizeImages(objGambar,240,135);
                            cG4L3.setIcon(objG4L3);
                        }
                        case 5 ->{
                            jG5.setVisible(true);
                            intDetail5 = Results.getInt("ID");
                            cG5L0.setText(Results.getString("Merek"));
                            cG5L1.setText(Results.getString("Model"));
                            cG5L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG5L3 = ResizeImages(objGambar,240,135);
                            cG5L3.setIcon(objG5L3);
                        }
                        default ->{
                            // Nothing
                        }
                    }
                }
            }
        } catch (SQLException ex){
            
        }
    }//GEN-LAST:event_jBackMouseClicked

    private void jNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNextMouseClicked
        jG0.setVisible(false);
        jG1.setVisible(false);
        jG2.setVisible(false);
        jG3.setVisible(false);
        jG4.setVisible(false);
        jG5.setVisible(false);
        
        try(Connection DB = DriverManager.getConnection(DBNAME, DBUSER, DBPASS)){
            try(PreparedStatement Statements = DB.prepareStatement("SELECT COUNT(*) AS listTotal FROM mobil")){
                ResultSet Results = Statements.executeQuery();
                if(Results.next()){
                    int currentData = Results.getInt("listTotal");
                    selectorOffset = !((currentData - selectorOffset) < 6) ? selectorOffset + 6 : selectorOffset;
                }
            }
            String Query = "SELECT ID, Merek, Model, Kapasitas, Gambar FROM mobil WHERE NOT(Status='Dipakai' OR Status='Perbaikan' OR Status='Dipesan') LIMIT 6 OFFSET ?";
            try(PreparedStatement Statements = DB.prepareStatement(Query)){
                Statements.setInt(1, selectorOffset);
                ResultSet Results = Statements.executeQuery();
                int index = 0;
                while(Results.next()){
                    switch (index++){
                        case 0 ->{
                            jG0.setVisible(true);
                            intDetail0 = Results.getInt("ID");
                            cG0L0.setText(Results.getString("Merek"));
                            cG0L1.setText(Results.getString("Model"));
                            cG0L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG0L3 = ResizeImages(objGambar,240,135);
                            cG0L3.setIcon(objG0L3);
                        }
                        case 1 ->{
                            jG1.setVisible(true);
                            intDetail1 = Results.getInt("ID");
                            cG1L0.setText(Results.getString("Merek"));
                            cG1L1.setText(Results.getString("Model"));
                            cG1L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG1L3 = ResizeImages(objGambar,240,135);
                            cG1L3.setIcon(objG1L3);
                        }
                        case 2 ->{
                            jG2.setVisible(true);
                            intDetail2 = Results.getInt("ID");
                            cG2L0.setText(Results.getString("Merek"));
                            cG2L1.setText(Results.getString("Model"));
                            cG2L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG2L3 = ResizeImages(objGambar,240,135);
                            cG2L3.setIcon(objG2L3);
                        }
                        case 3 ->{
                            jG3.setVisible(true);
                            intDetail3 = Results.getInt("ID");
                            cG3L0.setText(Results.getString("Merek"));
                            cG3L1.setText(Results.getString("Model"));
                            cG3L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG3L3 = ResizeImages(objGambar,240,135);
                            cG3L3.setIcon(objG3L3);
                        }
                        case 4 ->{
                            jG4.setVisible(true);
                            intDetail4 = Results.getInt("ID");
                            cG4L0.setText(Results.getString("Merek"));
                            cG4L1.setText(Results.getString("Model"));
                            cG4L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG4L3 = ResizeImages(objGambar,240,135);
                            cG4L3.setIcon(objG4L3);
                        }
                        case 5 ->{
                            jG5.setVisible(true);
                            intDetail5 = Results.getInt("ID");
                            cG5L0.setText(Results.getString("Merek"));
                            cG5L1.setText(Results.getString("Model"));
                            cG5L2.setText(Results.getString("Kapasitas"));
                            ImageIcon objGambar = new ImageIcon(Main.class.getResource(Results.getString("Gambar")));
                            objG5L3 = ResizeImages(objGambar,240,135);
                            cG5L3.setIcon(objG5L3);
                        }
                        default ->{
                            // Nothing
                        }
                    }
                }
            }
        } catch (SQLException ex){
            
        }
    }//GEN-LAST:event_jNextMouseClicked

    private void jDetail0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDetail0MouseClicked
        selectedDetails = intDetail0;
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pemesanan().setVisible(true));
    }//GEN-LAST:event_jDetail0MouseClicked

    private void jDetail3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDetail3MouseClicked
        selectedDetails = intDetail1;
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pemesanan().setVisible(true));
    }//GEN-LAST:event_jDetail3MouseClicked

    private void jDetail1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDetail1MouseClicked
        selectedDetails = intDetail2;
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pemesanan().setVisible(true));
    }//GEN-LAST:event_jDetail1MouseClicked

    private void jDetail4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDetail4MouseClicked
        selectedDetails = intDetail3;
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pemesanan().setVisible(true));
    }//GEN-LAST:event_jDetail4MouseClicked

    private void jDetail2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDetail2MouseClicked
        selectedDetails = intDetail4;
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pemesanan().setVisible(true));
    }//GEN-LAST:event_jDetail2MouseClicked

    private void jDetail5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDetail5MouseClicked
        selectedDetails = intDetail5;
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pemesanan().setVisible(true));
    }//GEN-LAST:event_jDetail5MouseClicked

    private void navItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems1ActionPerformed
        dispose();
        SwingUtilities.invokeLater(() -> new USER.Pesanan().setVisible(true));
    }//GEN-LAST:event_navItems1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JLabel cG0L0;
    private javax.swing.JLabel cG0L1;
    private javax.swing.JLabel cG0L2;
    private javax.swing.JLabel cG0L3;
    private javax.swing.JLabel cG1L0;
    private javax.swing.JLabel cG1L1;
    private javax.swing.JLabel cG1L2;
    private javax.swing.JLabel cG1L3;
    private javax.swing.JLabel cG2L0;
    private javax.swing.JLabel cG2L1;
    private javax.swing.JLabel cG2L2;
    private javax.swing.JLabel cG2L3;
    private javax.swing.JLabel cG3L0;
    private javax.swing.JLabel cG3L1;
    private javax.swing.JLabel cG3L2;
    private javax.swing.JLabel cG3L3;
    private javax.swing.JLabel cG4L0;
    private javax.swing.JLabel cG4L1;
    private javax.swing.JLabel cG4L2;
    private javax.swing.JLabel cG4L3;
    private javax.swing.JLabel cG5L0;
    private javax.swing.JLabel cG5L1;
    private javax.swing.JLabel cG5L2;
    private javax.swing.JLabel cG5L3;
    private javax.swing.JLabel jBack;
    private javax.swing.JLabel jDetail0;
    private javax.swing.JLabel jDetail1;
    private javax.swing.JLabel jDetail2;
    private javax.swing.JLabel jDetail3;
    private javax.swing.JLabel jDetail4;
    private javax.swing.JLabel jDetail5;
    private javax.swing.JPanel jG0;
    private javax.swing.JPanel jG1;
    private javax.swing.JPanel jG2;
    private javax.swing.JPanel jG3;
    private javax.swing.JPanel jG4;
    private javax.swing.JPanel jG5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jNext;
    private javax.swing.JButton navCS;
    private javax.swing.JButton navExit;
    private javax.swing.JButton navItems1;
    private javax.swing.JButton navItems2;
    private javax.swing.JButton navSettings;
    // End of variables declaration//GEN-END:variables
}
