/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ROOT.Karyawan;

import AUTH.Authenticate;
import Libraries.Auth;
import Libraries.Database;
import static Libraries.Database.DBNAME;
import static Libraries.Database.DBPASS;
import static Libraries.Database.DBUSER;
import javax.swing.SwingUtilities;
import Libraries.Variabel.Position;
import static Libraries.Variabel.UploadImages;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author surya
 */
public class Buat extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Buat() {
        initComponents();
    }
    
    public static File ImagesFile = null;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sidebar = new javax.swing.JPanel();
        navItems1 = new javax.swing.JButton();
        navItems2 = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        Gender = new javax.swing.JComboBox<>();
        Posisi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Kontak = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RENTAL | Karyawan Baru");
        setLocation(Position.Center("screenX"),Position.Center("screenY")
        );
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sidebar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navItems1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems1.setText("Simpan");
        navItems1.setAlignmentY(0.0F);
        navItems1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems1ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 184, 28));

        navItems2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        navItems2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow_circle_left_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        navItems2.setText("Kembali");
        navItems2.setAlignmentY(0.0F);
        navItems2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        navItems2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navItems2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navItems2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navItems2ActionPerformed(evt);
            }
        });
        Sidebar.add(navItems2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 364, 184, 28));

        getContentPane().add(Sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 400));

        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nama Pengguna");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 40));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel2.setText("Jenis Kelamin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 20));

        Nama.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 200, 25));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel9.setText("Nama Lengkap");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 20));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel10.setText(" : : Informasi Karyawan");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 15, 200, 20));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel12.setText("Username");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 225, 200, 20));

        Username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Username.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 245, 200, 25));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 275, 200, 20));

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel15.setText(" : : Informasi Akun");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 200, 20));

        Password.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 295, 200, 25));

        Gender.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Wanita" }));
        jPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 200, 25));

        Posisi.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.add(Posisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 200, 25));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Posisi Karyawan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 200, 20));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel11.setText(" : : Informasi Kontak");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 15, 200, 20));

        Kontak.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.add(Kontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 200, 25));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel14.setText("No. Telepon");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 200, 20));

        Email.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 200, 25));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel16.setText("Email");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 200, 20));

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel17.setText("Alamat");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 200, 20));

        Alamat.setColumns(21);
        Alamat.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        Alamat.setLineWrap(true);
        Alamat.setRows(5);
        Alamat.setTabSize(6);
        Alamat.setMinimumSize(new java.awt.Dimension(200, 23));
        jScrollPane1.setViewportView(Alamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 600, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(Auth.isLoggedIn() == false){
            dispose();
            
            SwingUtilities.invokeLater(() -> new Authenticate().setVisible(true));
        }
        try {
            jLabel4.setText(Database.SELECT("SELECT Nama FROM karyawan WHERE Username = ?"));
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        try(Connection DB = DriverManager.getConnection(DBNAME, DBUSER, DBPASS)){
            try(PreparedStatement Statements = DB.prepareStatement("SELECT Nama FROM utype"); ResultSet Results = Statements.executeQuery();){
                List<String> thisData = new ArrayList<>();
                while(Results.next()){
                    String preparedData = Results.getString("Nama");
                    thisData.add(preparedData);
                }
                
                for(String strPosisi: thisData){
                    Posisi.addItem(strPosisi);
                }
            }
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void navItems1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems1ActionPerformed
        String strUsername = Username.getText();
        String strPassword = Password.getText();
        String strNama = Nama.getText();
        String strPosisi = String.valueOf(Posisi.getSelectedItem());
        String strGender = String.valueOf(Gender.getSelectedItem());
        String strEmail = Email.getText();
        String strKontak = Kontak.getText();
        String strAlamat = Alamat.getText();
        
        try (Connection DB = DriverManager.getConnection(DBNAME, DBUSER, DBPASS)) {
            String Query = "SELECT ID FROM utype WHERE Nama=?";
            int intPosisi = 0;
            try(PreparedStatement Statements = DB.prepareStatement(Query)){
                Statements.setString(1,strPosisi);
                ResultSet Results = Statements.executeQuery();
                if(Results.next()){
                    intPosisi = Results.getInt("ID");
                }
            }
            String DBQuery = "INSERT INTO karyawan(Username,Password,Nama,Posisi,Gender,Email,Kontak,Alamat) VALUES(?,?,?,?,?,?,?,?)";
            try(PreparedStatement Statements = DB.prepareStatement(DBQuery)){
                Statements.setString(1, strUsername);
                Statements.setString(2, strPassword);
                Statements.setString(3, strNama);
                Statements.setInt(4, intPosisi);
                Statements.setString(5, strGender);
                Statements.setString(6, strEmail);
                Statements.setString(7, strKontak);
                Statements.setString(8, strAlamat);
                
                if(Statements.executeUpdate() > 0){
                    
                    dispose();
                    SwingUtilities.invokeLater(() -> new ROOT.Karyawan.Main().setVisible(true));
                } else{
                    JOptionPane.showMessageDialog(null, "Gagal menyimpan Data!","Peringatan",JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex){
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan sistem!\n" + ex.getMessage(),"Peringatan",JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan sistem!\n" + ex.getMessage(),"Peringatan",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_navItems1ActionPerformed

    private void navItems2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navItems2ActionPerformed
        dispose();
        SwingUtilities.invokeLater(() -> new ROOT.Karyawan.Main().setVisible(true));
    }//GEN-LAST:event_navItems2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JTextField Email;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField Kontak;
    private javax.swing.JTextField Nama;
    private javax.swing.JPasswordField Password;
    private javax.swing.JComboBox<String> Posisi;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton navItems1;
    private javax.swing.JButton navItems2;
    // End of variables declaration//GEN-END:variables
}
